# Generated by Django 5.0.6 on 2024-06-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='galeria_imagenes',
            field=models.TextField(blank=True, help_text='Ingrese URLs de imágenes separadas por comas'),
        ),
    ]
